### ISSUE TITLE
Send Order Confirmation

### ISSUE THREAD

**Issue by dzm-fiodarau** [dzm-fiodarau/SOEN341-Project#41]
As a user, I want to receive a confirmation that my order has been successfully processed when I finish the checkout process so that I would know no problem was encountered. (Reference to Epic User Story #10)

Story Points: 4 pts
Priority: Medium
Risk: High
Acceptance test:
- If no problem was encountered processing my order, i want to recieve confirmation that notifies me of that
- If there is a problem encountered when processing my order, i want to be notified of it
- If there is a problem encountered when processing my order, i want my order to be cancelled
- If there is a problem encountered when processing my order, i want my money refunded

**Comment by marwanGhaziri** [comment]
//  MailMessage class
System::SharedPtr<MailMessage> message = System::MakeObject<MailMessage>();
System::SharedPtr<SmtpClient> client = System::MakeObject<SmtpClient>();

// Set subject of the message, Html body and sender information (Must change the email )
message->set_Subject(u"New message created by Aspose.Email for .NET");
message->set_From(System::MakeObject<MailAddress>(L"from@domain.com", L"Sender Name", false));
message->set_Body(System::String(u"<b>This line is in bold.</b> <br/> <br/>") + u"<font color=blue>This line is in blue color</font>");
message->set_BodyEncoding(System::Text::Encoding::get_ASCII());
// Add TO recipients and Add CC recipients
message->get_To()->Add(System::MakeObject<MailAddress>(L"name1@domain.com", L"Recipient 1", false));
message->get_To()->Add(System::MakeObject<MailAddress>(L"name2@domain.com", L"Recipient 2", false));
message->get_CC()->Add(System::MakeObject<MailAddress>(L"cc1@domain.com", L"Recipient 3", false));

// Specify your mailing host server, Username, Password, Port # and Security option
client->set_Host(u"mail.server.com");
client->set_Username(u"username");
client->set_Password(u"password");
client->set_Port(587);
client->set_SecurityOptions(Aspose::Email::Clients::SecurityOptions::SSLExplicit);

try
{
	// Send this message
	client->Send(message);
}
catch (System::Exception& ex)
{
}

**Comment by dzm-fiodarau** [comment]
This is an additional feature that was not required but we can still implement it later as we already have the code for it.
